### ISSUE TITLE
Is the repo still supported by the authors?

### ISSUE THREAD

**Issue by daqo** [cmu-sei/BigGrep#2]
A couple of questions:
1. What are the best ways to to enable fast hex content search for binaries? Is the approach taken by this library still the best?
2. Is the repo still supported by the authors?

**Comment by sei-ccohen** [comment]
Sorry for the delay in responding.

1. We believe that BigGrep is a good binary search approach and we continue to use it.
2. We're not actively engaged in new feature development, but the code base is reasonably feature-complete.   It is supported, and we're happy to respond to specific questions or address any bugs that you might find.
